### ISSUE TITLE
Issue when using stem option: UnboundLocalError: local variable 'sources' referenced before assignment

### ISSUE THREAD

**Issue by Seanitzel** [Ryan5453/demucs#2]
Logs from replicate when trying to use the stem option:
```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cog/server/worker.py", line 354, in _predict
result = predict(**payload)
File "/src/predict.py", line 184, in predict
sources = list(sources)
UnboundLocalError: local variable 'sources' referenced before assignment
```

Pretty sure it's a bug in the code, as I don't know where sources is supposed to come from in that line for list(sources)...
Maybe it should be list(stem), but that would  mean stem would need to be an array...

**Comment by Ryan5453** [comment]
hi, thanks for making me aware of this. i believe i have found the issue but i'm running into a weird issue trying to build the cog to be able to test it but i'll try to fix this in the next few days

**Comment by Seanitzel** [comment]
Sounds great, thank you so much 😁

**Comment by Ryan5453** [comment]
This should be fixed.
